-- Seed 852 exercises from Wger (English) for local development.
-- Requires 20260610115000_exercise_library_schema.sql

INSERT INTO public.exercises (external_id, name, muscle_groups, equipment, category, search_aliases, is_custom)
SELECT v.external_id, v.name, v.muscle_groups, v.equipment, v.category, v.search_aliases, false
FROM (VALUES
  ('wger:1962', 'Step Jack', ARRAY['quads','shoulders','glutes','core'], ARRAY['bodyweight'], 'cardio', ARRAY['Side Step Jack','Low Impact Jumping Jack']),
  ('wger:1963', 'Slow Squat', ARRAY['quads','hamstrings','glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY['Tempo Squat','​3-1-1 Squat']),
  ('wger:1964', 'Wide Push-Up', ARRAY['chest','core','triceps'], ARRAY['bodyweight'], 'strength', ARRAY['Wide Grip Push-Up']),
  ('wger:1965', 'Marching High Knees', ARRAY['quads','calves','glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY['High Knee March','​Standing Knee Drives']),
  ('wger:1966', '1/2 Kneeling Thoracic Rotation', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1967', 'lento avanti seduto', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1968', 'Single-arm dumbbell shoulder press', ARRAY['shoulders','core','full_body','back','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1970', 'Kettlebell sumo high pull', ARRAY['back','shoulders','hamstrings','glutes','quads'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1971', 'Mentzer Pulldown', ARRAY['biceps','back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1972', 'Single-Arm Lat Pulldown', ARRAY['back','biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:31', 'Axe Hold', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:805', 'Tricep Pushdown on Cable', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:981', 'Step-ups', ARRAY[]::text[], ARRAY['bench'], 'strength', ARRAY['Chair steps']),
  ('wger:980', 'commando pull-ups', ARRAY['shoulders','biceps','back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1022', 'Single Arm Plank to Row', ARRAY['shoulders','biceps','full_body','back','core'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:820', 'Fingerboard 20 mm edge', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:828', 'Incline Bench Reverse Fly', ARRAY['shoulders','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:907', 'Handstand Push Up', ARRAY['shoulders','triceps','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:908', 'Zone 2 Running', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:923', 'LYING DUMBBELL ROW SS SEATED SHRUG', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:927', 'Suspended crossess', ARRAY['chest'], ARRAY['bodyweight'], 'cardio', ARRAY['croci','sospensione','trx']),
  ('wger:958', 'Biceps with TRX', ARRAY['biceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:960', 'Kettlebell Swing', ARRAY['shoulders','glutes','quads','core','back'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:961', 'Swimming 50m sprints', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:57', 'Bear Walk 2', ARRAY['shoulders','calves','chest','core','full_body','triceps','glutes','back','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:975', 'one-handed kettlebell curls', ARRAY['biceps'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:976', 'Medicine ball booklet crunch', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:977', 'Box squat', ARRAY['glutes','quads','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:978', 'Knee Raises', ARRAY['core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:804', 'Sloper hanging', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:41', 'Barbell Ab Rollout', ARRAY['core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:962', 'Elliptical', ARRAY['glutes','quads','back','biceps','core','triceps'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:983', 'High knees', ARRAY[]::text[], ARRAY['bodyweight'], 'cardio', ARRAY['Running in place']),
  ('wger:821', 'Pullup on fingerboard', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:985', 'Push-up rotations', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY['Push up rotations','Pushup rotations']),
  ('wger:990', 'Kneeling kickbacks', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:909', 'Reverse Nordic Curl', ARRAY['quads','glutes','core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:912', 'Straight Bar Cable Curls', ARRAY['biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:924', 'Cable Fly', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:993', 'Jump rope: basic jumps', ARRAY[]::text[], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:959', 'TRX Rows', ARRAY['shoulders','biceps','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:979', 'Leg raises pull up bar', ARRAY['core','quads'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:996', 'Mountain climbers', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:997', '4-count burpees', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:998', 'No push-up burpees', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY['No push up burpees','No pushup burpees']),
  ('wger:1000', 'Floor dips', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1002', 'Child''s pose', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY['Prayer pose','Prayer pose']),
  ('wger:1003', 'Kettlebell deadlifts', ARRAY[]::text[], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:112', 'Body-Ups', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY['Body up']),
  ('wger:79', 'Bent High Pulls', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1006', 'Chin tuck', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1007', 'Head turns', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1010', 'Back neck stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1630', 'Blaze', ARRAY['shoulders','glutes','chest','quads','biceps','hamstrings','back','core'], ARRAY['bench','dumbbell','kettlebell','bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1969', 'Single-arm cable pushdown', ARRAY['triceps','core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1012', 'Alternating bicep curls', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1018', 'Head tilts', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:910', 'Nordic Curl', ARRAY['hamstrings','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:913', 'Reverse Preacher Curl (Close Grip)', ARRAY['biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:925', 'SMITH MACHINE SLIGHT INCLINE PRESS', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:154', 'Chin-ups', ARRAY['back'], ARRAY['other'], 'strength', ARRAY['Chin up','Chinup']),
  ('wger:132', 'Burpees', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:129', 'Chest Press', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:161', 'Cross-Bench Dumbbell Pullovers', ARRAY['back','chest','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:182', 'Deadhang', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:177', 'Cycling', ARRAY['core','back','hamstrings','full_body','glutes','quads'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:145', 'Cable Woodchoppers', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:178', 'Deadbug', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:152', 'Chin Up', ARRAY[]::text[], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:222', 'Facepull', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY['Face pull']),
  ('wger:914', 'Reverse EZ Bar Cable Curls', ARRAY['biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:926', 'Machine chest fly', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:208', 'Dumbbells on Scott Machine', ARRAY['biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:301', 'Hyperextensions', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:285', 'High Knee Jumps', ARRAY['hamstrings','calves','quads','full_body','core'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:901', 'Barbell Hip Thrust', ARRAY['glutes'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:915', 'BUS DRIVERS', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:279', 'Hand Grip', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:292', 'Hip Raise, Lying', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:284', 'Hercules Pillars', ARRAY['biceps','full_body','triceps','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:294', 'Hip Thrust', ARRAY['glutes'], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:289', 'High Pull', ARRAY['shoulders','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:297', 'Hollow Hold', ARRAY['core'], ARRAY['other','bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1634', 'Rope Pullover/row', ARRAY['back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1637', 'Single arm row', ARRAY['back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1638', 'Barbell Clean and press', ARRAY['shoulders','chest'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:310', 'Incline Dumbbell Row', ARRAY['back'], ARRAY['dumbbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:268', 'Good Mornings', ARRAY['hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:827', 'Front Plate Raise', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:916', 'Smith Press', ARRAY['shoulders'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:314', 'Isometric Wipers', ARRAY['chest','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:320', 'Jumping Jacks', ARRAY['quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:346', 'Landmine press', ARRAY['shoulders','chest','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:323', 'Cable Cross-over', ARRAY['chest','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:319', 'Jogging', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:395', 'Long-Pulley, Narrow', ARRAY['back','biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:917', 'Straight Bar Cable Front Raise', ARRAY['shoulders'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:957', 'Quadriped Arm and Leg Raise', ARRAY['shoulders','glutes','full_body','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:394', 'Long-Pulley (low Row)', ARRAY['back','biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:406', 'Lying Rotator Cuff Exercise', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:423', 'Muscle up', ARRAY['biceps','hamstrings'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:382', 'L Hold', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:468', 'Prone Scapular Retraction - Arms at Side', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:454', 'Pike Push Ups', ARRAY['chest','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:918', 'Seated Dumbbell Side Lateral', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:439', 'Overhand Cable Curl', ARRAY['biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:495', 'Reverse Curl', ARRAY['biceps','full_body'], ARRAY['barbell','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:919', 'T-Bar row', ARRAY['back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:516', 'Front Wood Chop', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:505', 'Roman Chair Crunch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1635', 'Modified pulldown', ARRAY['back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1029', 'Quadruped thoracic rotation right', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1639', 'Dumbbell Bent Over Face Pull', ARRAY['shoulders','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1713', 'Doorway Pectoral Stretch', ARRAY['chest'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:527', 'Run', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:539', 'Incline Bench Press - MP', ARRAY['chest','shoulders','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:500', 'Reverse Plank', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:577', 'Side Dumbbell Trunk Flexion', ARRAY['core'], ARRAY['dumbbell'], 'strength', ARRAY['Side bends']),
  ('wger:578', 'Side-lying External Rotation', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:595', 'Skipping - Standard', ARRAY['calves'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:556', 'Side Bends on Machine', ARRAY['core'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:624', 'Stationary Bike', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:655', 'Tricep Dumbbell Kickback', ARRAY['triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:636', 'Superman', ARRAY['glutes','back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:661', 'Triceps on Machine', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:623', 'Standing Rope Forearm', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:675', 'Turkish Get-Up', ARRAY['shoulders','glutes','core','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:922', 'SEATED CABLE MID TRAP SHRUG', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:974', 'Curl with kettlebell two hands', ARRAY['biceps'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:683', 'Power Clean', ARRAY['chest'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:722', 'Weighted Step-ups', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:688', 'Upper External Oblique', ARRAY['core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:672', 'Trunk Rotation With Cable', ARRAY['core','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:716', 'Wall Slides', ARRAY['biceps','hamstrings','chest','back','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:687', 'Overhead Press', ARRAY['shoulders'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1027', 'Elevated prayer stretch', ARRAY['back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1028', 'Quadruped thoracic rotation left', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1080', 'Hindu Pushups', ARRAY['shoulders','chest','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1081', 'Shoulder dislocates', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1082', 'Bent over row to external rotation', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1083', 'YWTs', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1086', 'Close-grip Press-ups', ARRAY['full_body','back','chest','shoulders','biceps','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1087', 'Dumbbell Hang Power Cleans', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1088', 'Dumbbell sumo deadlift', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1089', 'Medicine ball twist', ARRAY['core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1090', 'Vpushup', ARRAY['chest','quads','core','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1091', 'Plank Shoulder Taps', ARRAY['shoulders','glutes','core','back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1636', 'Unilateral Cable row', ARRAY['back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1640', 'Dumbbell Front Squat', ARRAY['glutes','quads','shoulders','core'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1641', 'Kettlebell One Legged Deadlift', ARRAY['glutes'], ARRAY['dumbbell','kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1642', 'Dumbbell Hip Thrust', ARRAY['glutes','quads'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1645', 'Dumbbell Shrug', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1648', 'Weighted Crunch', ARRAY['core'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1650', 'Dumbbell Side Bend', ARRAY['core'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1651', 'Dumbbell Rear Lunge', ARRAY['glutes','quads','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1653', 'Dumbbell Side Squat', ARRAY['glutes','quads','hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1654', 'Machine lateral wise', ARRAY['shoulders'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1655', 'Machine Chest Press Exercise', ARRAY['chest','triceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1104', 'Walking', ARRAY['hamstrings','calves','glutes','back','core','quads'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1188', 'Flexión lateral', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1652', 'Dumbbell Romanian Deadlift', ARRAY['hamstrings','glutes'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:911', 'Incline Skull Crush', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:829', 'Rear Delt Raise', ARRAY['shoulders','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1011', 'Front neck stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:9', '2 Handed Kettlebell Swing', ARRAY[]::text[], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1093', 'Rowing Machine', ARRAY['shoulders','biceps','hamstrings','full_body','calves','glutes','back','core','quads'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1094', 'Seated Bench Press', ARRAY['chest'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:84', 'Bent Over Rowing Reverse', ARRAY['back','shoulders','biceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1096', 'Abduction while standing', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1098', 'Seated rear delt rise', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1099', 'Dynamic side hold', ARRAY['core'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1100', 'Wall balls', ARRAY['shoulders','glutes','quads','biceps','chest','core','back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1101', 'Horizontal traction isometry', ARRAY['back','chest','shoulders','biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1102', 'Alternate back lunges', ARRAY['glutes','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1103', 'walking bridge', ARRAY['core','shoulders','biceps','glutes','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1105', 'Seated Knee Tuck', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1109', 'Cable Concentration Curl', ARRAY['biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1111', 'Push-Ups | Incline', ARRAY['chest','triceps'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1112', 'Push-Ups | Decline', ARRAY['chest','shoulders','triceps'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1113', 'Push-Ups | Parallettes', ARRAY['chest','shoulders','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1114', 'Rest (for timed workouts)', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1115', '3D lunge warmup', ARRAY[]::text[], ARRAY['dumbbell'], 'cardio', ARRAY[]::text[]),
  ('wger:1116', 'Dumbbell farmer''s carry', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1119', 'Remo maquina agarre estrecho', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1120', 'Remo maquina agarre estrecho supino', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1124', 'Jalón abierto', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1125', 'Jalón abierto supino', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1126', 'Jalón cerrado', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1127', 'Jalón cerrado supino', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1131', 'Extensión de gluteos en polea', ARRAY['glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1132', 'Extensión de gluteo en  máquina', ARRAY['glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1136', 'JALONES PECHO NEUTRO', ARRAY['biceps','back','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1137', 'PULL OVER POLEA ALTA', ARRAY['back','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1138', 'JALON EN BANCO INCLINADO', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1141', 'Arabesque', ARRAY['hamstrings','glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1143', 'Back extensión', ARRAY['back','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1185', 'Triceps Pushdown', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1186', 'One Arm Bent Row', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1190', 'Curl de biceps con agarre prono', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1192', 'Alternating Biceps Curls With Dumbbell', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1193', 'Russian Twist', ARRAY['back','core'], ARRAY['dumbbell','other'], 'strength', ARRAY[]::text[]),
  ('wger:1194', 'PALLOF PRESS', ARRAY['shoulders','glutes','core','full_body','back','chest','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1195', 'Side Slides + Squats', ARRAY['quads','calves','glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1196', 'Wall Drills', ARRAY['quads','calves'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1198', 'Inverted Rows', ARRAY['biceps','back','chest','core'], ARRAY['bodyweight'], 'strength', ARRAY['horizontal pull-ups']),
  ('wger:1200', 'Tibialis raises', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1201', 'Dragon squat', ARRAY['quads','hamstrings','calves','glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1202', 'Side Lying Hip Abduction', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1203', 'Calf raises, left leg', ARRAY['calves'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1204', 'Cycling cardio session', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1205', 'Wrist curl, dumbbells', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1207', 'Scorpion Kick', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1208', 'Prisoner Squat', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1210', 'Skydiver with arms in T-position', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:260', 'Full Sit Outs', ARRAY['glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1215', 'Reverse Snow Angel', ARRAY['back','shoulders','hamstrings','glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1216', 'Recruitment Pulls', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1217', 'Finger Pushup', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY['Flexão de dedo']),
  ('wger:1218', 'knee push-ups', ARRAY['shoulders','chest','full_body','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1219', 'Australian pull-ups', ARRAY['shoulders','biceps','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1656', 'Cable Chest Press - Decline', ARRAY['chest','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1714', 'Shoulder Dumbbell Pendular Exercise', ARRAY['shoulders','back','chest'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1715', 'Shoulder External Rotation with Dumbbell', ARRAY['shoulders','full_body','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1223', 'Claps over the head', ARRAY['shoulders'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1224', 'Dumbbell drag curls', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:369', 'Leg Extension', ARRAY['quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1716', 'Incline Shoulder Press Up', ARRAY['shoulders','chest'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1225', 'Dumbbell wide bicep curls', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1717', 'Neck extension', ARRAY['biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1226', 'Dumbbell bicep curl to press', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1227', 'Dumbbell rear delt row', ARRAY['shoulders','full_body','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1228', 'Dumbbell close grip bench press', ARRAY['chest','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:599', 'Snach', ARRAY['shoulders'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1230', 'Triceps stretch left', ARRAY['triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:921', 'Seated Cable Rows', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1231', 'Triceps stretch right', ARRAY['triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1232', 'Standing biceps stretch left', ARRAY['shoulders','biceps','chest'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1233', 'Standing biceps stretch right', ARRAY['shoulders','biceps','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1234', 'Dumbbell Single-leg Hip Thrust', ARRAY['glutes','hamstrings','quads'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1718', 'Remo alto polea alta', ARRAY['core','full_body','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1238', 'Frog stand', ARRAY['shoulders','biceps','full_body','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1239', 'Standing Calf Stretch', ARRAY['calves'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1092', 'Bag training', ARRAY['shoulders','chest','back','biceps','hamstrings','calves','core'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1240', 'Standing Soleus Stretch', ARRAY['full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1241', 'Exercise Band Dorsiflexion', ARRAY['full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1117', 'Seated Cable Row', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1242', 'Exercise Band Plantarflexion', ARRAY['calves','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1243', 'Double Leg Calf Raise', ARRAY['calves','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1244', 'Yoga exercise: Cow-cat', ARRAY['shoulders','back','core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1245', 'Front Lever', ARRAY['back','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1209', 'Shoulder width three-point push-up', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1246', 'TRX roll out', ARRAY['core','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1248', 'Ice Scream maker', ARRAY['back','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:851', 'Leg Extension', ARRAY['quads','hamstrings'], ARRAY[]::text[], 'strength', ARRAY['Extension Leg']),
  ('wger:1252', 'Front lever pull-up', ARRAY['biceps','back','core','shoulders'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1214', 'Front lever tuck', ARRAY['shoulders','biceps','back','triceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1259', 'TRX Obliques', ARRAY['core','full_body','shoulders','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1260', 'TRX hammer curl', ARRAY['biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:142', 'Cable External Rotation', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1261', 'TRX gorilla biceps curl', ARRAY['full_body','biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1262', 'Trx Single Arm Bicep Curl', ARRAY['biceps','full_body','shoulders','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1263', 'Back bridge', ARRAY['shoulders','hamstrings','calves','back','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1266', 'TRX Tricep Extension', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1269', 'TRX dips', ARRAY['triceps','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1270', 'Low Pulley Cable Fly', ARRAY['chest','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1273', 'Pullover', ARRAY['chest','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1274', 'Sitting Calf Stretch (Dorsiflexion)', ARRAY['calves','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1275', 'Plantarflexion Stretch with Band', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1277', 'Incline Dumbbell Press', ARRAY['chest','shoulders','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1280', 'Biceps Close Grip Pull Down', ARRAY['biceps','shoulders','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1282', 'Isometria trazioni impugnatura inversa', ARRAY['back','biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1283', 'Incline Chest-Supported Dumbbell Row', ARRAY['biceps','back'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1284', 'Pseudo Planche Push-up', ARRAY['shoulders','chest'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1285', 'Talons fesses', ARRAY['calves','hamstrings'], ARRAY['bodyweight'], 'cardio', ARRAY['Bum kicks']),
  ('wger:1286', 'Dynamic Planche', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1287', 'Reach ups', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1288', 'Planche de cote dynamique', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1289', 'Seated Dumbbell Curls', ARRAY['biceps','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1290', 'Reverse Grip Barbell Curls', ARRAY['biceps','full_body'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1292', 'Trazioni impugnatura inversa', ARRAY['biceps','back','core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1293', 'One armed push-ups', ARRAY['chest','triceps','shoulders','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1294', 'Arco femorale una gamba', ARRAY['glutes','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1296', 'Low-Cable Cross-Over - NB', ARRAY['chest','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1298', 'High-Cable Cross Tricep Extention - NB', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1657', 'Preacher Curl - Internally Rotated', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1659', 'Lat Pulldown - Cross Body Single Arm', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1660', 'Cable Chest Press - Incline', ARRAY['chest','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1302', 'JM Press', ARRAY['triceps','biceps','chest'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1303', 'Helms Row', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1304', 'Meadows Row', ARRAY['back','biceps','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1661', 'Cable Triceps Press', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1662', 'Cable Tri Extension - Internal Rotation', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1307', 'Front Plank', ARRAY['core','chest','quads','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1666', 'Curl  - With Shoulder Elevated', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1313', 'Lying Leg Raise', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1314', 'Jumping Jack HD', ARRAY['quads','glutes','core'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1388', 'Single Leg RDL', ARRAY['hamstrings','glutes'], ARRAY['bodyweight'], 'strength', ARRAY['Single Leg Romanian Deadlift']),
  ('wger:1318', 'High Knee Skips HD', ARRAY['core','biceps','glutes','quads','triceps'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1319', 'Crunches HD', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1320', 'Bench Dips On Floor HD', ARRAY['biceps','full_body','triceps','shoulders','chest','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1322', 'Kopfüber Gewichtaufheben', ARRAY['core'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1324', 'Bodyweight lunge HD', ARRAY['quads','glutes','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1325', 'Lateral Push Off', ARRAY['calves','hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1668', 'One Arm Overhead Cable Tricep Extension', ARRAY['triceps'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1670', 'Leg Swings (Front–Back)', ARRAY['hamstrings','glutes','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1672', 'Seated Hip Abduction', ARRAY['glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1333', 'Forearm Curls (underhand grip)', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1336', 'Triceps Overhead (Dumbbell)', ARRAY['triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1338', 'Schoulder Raise (Dumbbell)', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1679', 'Wall Angels', ARRAY['back','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1680', 'seated figure four', ARRAY['glutes'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1348', 'Lower Back Extensions', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1353', 'Dumbbell Hex Press', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1360', 'Double Kettlebell Clean and Press', ARRAY['shoulders','biceps','full_body','quads','back','triceps','hamstrings','glutes','core'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1361', 'Double Kettlebell Front Squat', ARRAY['glutes','quads','hamstrings','calves','core'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1363', 'Blackroll', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1366', 'Dumbbell Split Squat', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1370', 'Dumbbell Deadlift', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1373', 'box jumps', ARRAY['glutes','calves'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1374', 'Rotary Torso Machine', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1376', 'Recumbent Bike', ARRAY['hamstrings','calves','glutes','quads'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1377', 'TORSO TWIST', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1380', 'Band pull-aparts', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1381', 'Upper Back', ARRAY['shoulders','back','biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1312', 'Bodyweight Squat HD', ARRAY['quads','calves','glutes','core','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1384', 'Pullover Machine', ARRAY['back','chest','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1683', 'Zottman curl', ARRAY['biceps','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:650', 'Thruster', ARRAY['shoulders','back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1387', 'Hamstring Kicks', ARRAY['hamstrings','glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1390', 'Toe Touch', ARRAY['hamstrings','glutes','calves'], ARRAY['bodyweight'], 'strength', ARRAY['Standing Forward Bend']),
  ('wger:1684', 'Dumbbell Thruster', ARRAY['hamstrings','glutes','quads','shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1686', 'Glute Bridge Single-Arm Press', ARRAY['chest','shoulders','biceps','hamstrings','glutes','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1687', 'Bear crawl pull through', ARRAY['shoulders','glutes','quads','core','hamstrings','calves','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1372', 'Triceps Dips (Assisted)', ARRAY['triceps','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1378', 'Cable Lateral Raises (Single Arm)', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1391', 'Elephant Walks', ARRAY['hamstrings','calves'], ARRAY['bodyweight'], 'strength', ARRAY['Walking Hamstring Stretch']),
  ('wger:1392', 'Good Morning', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY['Hip Hinge']),
  ('wger:1393', 'Single Leg Hamstring Stretch', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY['Seated Single Leg Stretch']),
  ('wger:1394', 'Sit & Reach', ARRAY['hamstrings'], ARRAY['other'], 'strength', ARRAY['Seated Forward Bend','Seated Toe Touches']),
  ('wger:1395', 'Crossbody Leg Swings', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY['Lateral Leg Swings']),
  ('wger:1396', 'Standing Pancake', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1398', 'Hamstring Chokes', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY['Dynamic Hamstring Stretch']),
  ('wger:1399', 'Roll Down', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1400', 'Crossbody Hamstring Stretch', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY['Standing Cross-Leg Hamstring Stretch']),
  ('wger:1658', 'Preacher Curl - Externally Rotated', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1406', 'Plank-to-Elbow Extension', ARRAY['shoulders','core','triceps','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1407', 'Cossack squat', ARRAY['glutes','quads','calves','core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1408', 'Wall-sit', ARRAY['glutes','quads','calves','core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1409', 'Dragon-flag', ARRAY['core','shoulders','glutes','back','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1410', 'Plank with Alternating Leg Lift', ARRAY['glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1411', 'Heel Touches', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1412', 'bicycle crunches', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1414', 'Hack Squats', ARRAY['quads','hamstrings','calves','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1415', 'Dumbbell Crunches', ARRAY['core'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1424', 'Biceps Curl Machine', ARRAY['biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1425', 'Toe Taps', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1426', 'Standing Side Crunches', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1429', 'Dumbbell Shoulder Rotations', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1430', 'Plate Pinch Hold', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1433', 'Reverse Wood Chops', ARRAY['glutes','back','shoulders','biceps','core','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1434', 'Lat Pull DB', ARRAY['back','glutes'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1435', 'Scapula Pulls', ARRAY['back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1436', 'Pin Bench Press BB', ARRAY['chest','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1437', 'Pin Squat', ARRAY['hamstrings','glutes','quads','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1438', 'Clean', ARRAY['glutes','quads','hamstrings','back','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1439', 'Pin OHP', ARRAY['shoulders','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1440', 'Push OHP', ARRAY['shoulders','glutes','quads','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1441', 'Incline OHP DB', ARRAY['shoulders','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1442', 'Kreis Press DB', ARRAY['shoulders','biceps','chest','core','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1443', 'Shoulder Raise Side and Front DB', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1444', 'Incline Chest Press DB', ARRAY['chest','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1445', 'Jerk OL', ARRAY['shoulders','glutes','quads','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1446', 'Clean and Jerk OL', ARRAY['shoulders','hamstrings','glutes','quads','back','core','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1447', 'Snatch OL', ARRAY['shoulders','hamstrings','glutes','quads','back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1448', 'Seated W Curl', ARRAY['biceps','full_body'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1449', 'ClimbMill', ARRAY['quads','hamstrings','glutes'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1450', 'Cobra Stretch', ARRAY['core','chest'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1451', 'Torso rotation stretch', ARRAY['core','chest'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1452', 'Knee to Chest Stretch', ARRAY['glutes','hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1455', 'Towel Superman', ARRAY['back','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1457', 'Cable Press Around', ARRAY['shoulders','chest','triceps','biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1458', 'Cross-Body Cable Y-Raise', ARRAY['shoulders','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1461', 'No Leg Drive Dumbbell Chest Press', ARRAY['chest','shoulders','triceps'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1462', 'punches', ARRAY['shoulders','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1463', 'Dumbbell Underhand Dead Row', ARRAY['biceps','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1464', 'Pause Hack Squats', ARRAY['quads','hamstrings','calves','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1465', 'Spider Curl', ARRAY['biceps'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1466', 'Calf Raise using Hack Squat Machine', ARRAY['calves','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1467', 'Incline Close Grip Barbell Bench Press', ARRAY['triceps','shoulders','chest'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1468', 'Floor Skull Crusher', ARRAY['triceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1469', 'Bent over Cable Flye', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1470', '1-Arm Half-Kneeling Lat Pulldown', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1471', 'Kroc Row', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1472', 'Cable Shrug-In', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1473', 'Reverse Cable Flye', ARRAY['shoulders','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1474', 'W-Raise', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1475', 'Black Widow Knee Slides', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1476', 'Butterfly Sit Up', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1477', 'Seated Corkscrew', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1478', 'Levitation Crunch', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1479', 'Sit Up Elbow Thrust', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1480', 'Lying Triceps Extensions', ARRAY['triceps'], ARRAY['barbell','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1481', 'Drag Pushdown', ARRAY['triceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1482', 'Dumbbell Cheat Curl', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1483', 'Bizeps Curls Trifecta', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1484', 'Omni Cable Cross-over', ARRAY['chest'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1485', 'Rocking Triceps Pushdown', ARRAY['triceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1486', 'Alternating High Cable Row', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1487', 'Hyper Y W Combo', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1488', 'Dumbbell Pullover', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1489', 'Plank Jacks', ARRAY['glutes','core','calves','quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1490', 'Lying Triceps Kickback', ARRAY['triceps'], ARRAY['dumbbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:1491', 'Remada unilateral no cabo', ARRAY['back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1492', 'High Row', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1493', 'Bayesian Curl', ARRAY['biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1496', 'DB Upper Chest Variation', ARRAY['chest','shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1497', 'DB Underhand bench press', ARRAY['chest','shoulders'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1498', 'Elbows Tucked DB Bench Press', ARRAY['triceps','chest'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1500', 'DB UCV', ARRAY['chest','shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1501', 'Alternative DB Gorilla rows', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1502', 'DB Cross Body Hammer Curls', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1503', 'Dumbbell Frog Press', ARRAY['glutes'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1504', 'Dumbbell Bradford press', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1689', 'Cable Fly Middle Chest', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1690', 'Cable Fly Upper Chest', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1508', 'High-Incline Smith Machine Press', ARRAY['shoulders','chest','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1509', 'Cable Tricep Kickback', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1510', 'Neutral Grip Lat Pulldown', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1511', 'Kong Curl', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1512', 'Drop Curl', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1513', 'Overhead Cable Tricep Extension', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1514', 'Lateral Walk', ARRAY['glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1515', 'Leg Press Toe Press', ARRAY['calves'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1516', 'Handstand', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1691', 'Cable Fly Lower Chest', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1692', 'Incline Smith Press', ARRAY['chest'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1519', 'Overhead Triceps Extension', ARRAY['back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1693', 'Incline Static Hold', ARRAY['chest'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1521', 'Pendular hack', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1694', 'Flat Machine Press', ARRAY['chest'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1523', 'Sled Push', ARRAY['calves','glutes','quads','shoulders','hamstrings','triceps'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1524', 'Battle Ropes', ARRAY['hamstrings','glutes','back','core','quads','shoulders','biceps','chest','triceps'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1525', 'Ball Slams', ARRAY['back','core','shoulders','glutes'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1526', 'Ski Machine', ARRAY['calves','back','triceps','hamstrings','glutes','quads','core'], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1527', 'Pendulum Squat', ARRAY['quads','hamstrings','glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1528', 'Glute Drive', ARRAY['glutes','hamstrings','quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1529', 'Toes to bar', ARRAY[]::text[], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1530', 'Lying Dumbbell Curls', ARRAY['biceps'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1531', 'Cable Curls', ARRAY['biceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1695', 'Pull-Ups (Wide Grip)', ARRAY['back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1698', 'Barbell Row (Overhand)', ARRAY['back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1699', 'Barbell Row (Underhand)', ARRAY['back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1536', 'Delt Stretch', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1537', 'Pull-up Isometric Hold', ARRAY['biceps','back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1700', 'Barbell Romanian Deadlift (RDL)', ARRAY['back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1701', 'One-Arm Heavy Row', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1702', 'Jalón al pecho con agarre ancho', ARRAY['back','biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1703', 'Patadas traseras', ARRAY['triceps'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1542', 'Wide Pull Up', ARRAY['back'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1704', 'Tuck L-sit', ARRAY['core','full_body','chest','quads','back','triceps'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1545', 'Archer Pull Up', ARRAY['back','biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1546', 'Larsen Press', ARRAY['chest','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1706', 'Bulgarian Squat with Dumbbells', ARRAY['glutes','quads','hamstrings'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1548', 'Stair Master', ARRAY['hamstrings','calves','glutes','quads'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1707', 'Elevación lateral polea', ARRAY['shoulders'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1710', 'Butchers Block Stretch', ARRAY['back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1554', 'Clap Push-UP', ARRAY['chest','shoulders','core','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1711', 'Sleeper Stretch', ARRAY['shoulders','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1551', 'Push-Up', ARRAY['chest','shoulders','core','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1556', 'Devil’s Press', ARRAY['shoulders','glutes','chest','hamstrings','back','core','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1572', 'Bird Dog', ARRAY['core','shoulders','glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1573', 'Ab wheel', ARRAY['core','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1574', 'Schwimmen', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1575', 'Standing Dowel Shoulder press', ARRAY[]::text[], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1576', 'Snap Down', ARRAY['hamstrings','glutes','quads','calves','core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1577', 'Bretzel stretch', ARRAY['glutes','hamstrings','back','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1578', 'Hip hinge', ARRAY['hamstrings','glutes','calves','quads','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1579', 'Bronco', ARRAY[]::text[], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1580', 'Perpendicular Unilateral Landmine Row', ARRAY['shoulders','back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1581', 'Trap press', ARRAY['back'], ARRAY['barbell','bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1582', 'Side-laying interior rotation', ARRAY['back'], ARRAY['barbell','bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1583', 'Supine press', ARRAY['back'], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:1584', 'March or jog in place', ARRAY['hamstrings','calves','glutes','quads','shoulders','biceps','core','triceps'], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1589', 'Estiramiento de piernas y cadera', ARRAY['hamstrings','glutes','quads','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1590', 'Estiramiento de brazos y cuello', ARRAY['shoulders','back','triceps','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1591', 'Respiración profunda (de pie o sentado)', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1592', 'Meditación guiada o libre', ARRAY[]::text[], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1593', 'Smith Machine Split Squat', ARRAY['hamstrings','quads'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1696', 'Pull-Ups (Neutral Grip)', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1709', 'Reverse Fly Standing', ARRAY['shoulders','back'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1712', 'Horizontal Shoulder Flexion Stretch', ARRAY['chest','shoulders'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1719', 'Jalon caballero unialteral', ARRAY['full_body','core'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1938', 'Cat-Cow', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1602', 'Dumbbell Scaption', ARRAY['back','shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1603', 'Leg curl with elastic', ARRAY['calves','hamstrings'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1604', 'Sliding Lateral Lunge', ARRAY['hamstrings','glutes','quads','calves','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1605', 'Copenhagen Adduction Exercise', ARRAY['glutes','quads','core','full_body','back'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1606', 'Arm Raises (T/Y/I)', ARRAY['shoulders','back','full_body','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1607', 'Typewriter Pull-ups', ARRAY['biceps','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1608', 'Bodyweight Biceps Curl', ARRAY['biceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1723', 'Glute Kickback (Machine)', ARRAY['glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1724', 'Standing Adduction (Cable)', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1725', 'Seated Row (Machine)', ARRAY['back','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1612', 'kettlebell sumo deadlift', ARRAY['hamstrings','glutes','quads'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1613', 'rubber band glute kickback', ARRAY['glutes'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1615', 'Treadmill Cardio', ARRAY[]::text[], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1616', 'Patada de burro con mancuerna', ARRAY['hamstrings','glutes'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1952', 'SMR Glutes (lax ball)', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1618', 'Cardio en bicicleta estática', ARRAY[]::text[], ARRAY['bodyweight'], 'cardio', ARRAY[]::text[]),
  ('wger:1726', 'Straight-Arm Pulldown (Cable)', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1620', 'Seated Dumbbell Calf Raise', ARRAY['calves'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1621', 'Unilateral Cable row', ARRAY['back','full_body'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1727', 'Side Straight-Arm Pulldown (Cable)', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1728', 'Shoulder Internal Rotation (Cable)', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1729', 'Shoulder External Rotation (Cable)', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1730', 'Side Lateral Raise (Cable)', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1731', 'Front Raise (Cable)', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1732', 'Face pulls with yellow/green band', ARRAY['back'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1733', 'Isometric Squat to Failure', ARRAY['glutes','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1734', 'Single-Leg Lunge with Kettlebell:', ARRAY['calves','glutes','quads'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:1735', 'Single-leg side glute press', ARRAY['calves','glutes','quads'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1737', 'Assisted chin-ups', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1738', 'Neutral-grip pull-ups or TRX rows', ARRAY['back','biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1739', 'Shrimp Squad', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1741', 'L-Sit Pull-ups', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1742', 'Back Lever', ARRAY[]::text[], ARRAY['other','bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1743', 'Windshield Wipers', ARRAY['core'], ARRAY['other','bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1744', 'Machine Side Lateral Raises', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1745', 'Cable Front Raise with a small bar', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1747', 'Smith machine squat', ARRAY['glutes','quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1751', 'Cable pull through', ARRAY['glutes','hamstrings','calves','quads','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1752', 'Side lateral raise - Front (Cable)', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1753', 'Side lateral raise - Back (Cable)', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1754', '45° lateral raises', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1755', 'Shoulder Y-pull cable', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1766', 'Plank Reach', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1768', 'bicep', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1769', 'cabel', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1772', 'Reverse crunch', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1773', 'Legend Incline Bench Press', ARRAY['chest','shoulders','triceps'], ARRAY[]::text[], 'strength', ARRAY['LeverEdge Machine Incline Press']),
  ('wger:1736', 'Single-Leg Deadlift with Dumbbell', ARRAY['hamstrings','glutes'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1740', 'Single Leg Glute Bridge', ARRAY['glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1748', 'Machine Hip Abduction', ARRAY['glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1771', 'Wrist curl, cable', ARRAY['biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1774', 'Chair dips', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1775', 'Pec deck rear delt fly', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1777', 'Deficit Push ups', ARRAY['chest','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1843', 'Butterfly Stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1844', 'Frog Stretch', ARRAY['glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1778', 'Supino inclinado', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1779', 'Landmine Rotation', ARRAY[]::text[], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1793', 'Supino Inclinado', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1795', 'unilateral cross body cable pull down', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1800', 'Supino Inclinado', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1803', 'Trap Bar Squat', ARRAY['quads','hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1804', 'ankle dorsiflexion rocks', ARRAY['calves','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1806', 'Lat Pull Down', ARRAY['back','shoulders','full_body'], ARRAY[]::text[], 'strength', ARRAY['lat Pulldown','Pulldown']),
  ('wger:1808', 'Parallel Bar Hold', ARRAY['shoulders','chest','triceps','back','core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1809', 'Reverse Hyperextension', ARRAY['hamstrings','glutes'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1810', 'Sphinx', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1822', 'Open Book', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1824', 'Dumbell Tate Press', ARRAY['triceps','shoulders','chest'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1825', 'Chest-Supported Rear Delt Raise', ARRAY['shoulders','back'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1826', 'Band pull-apart with external rotation', ARRAY['shoulders'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1827', 'Double-Leg Abdominal Press', ARRAY['core'], ARRAY['other','bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1828', 'Abdominal Draw-In', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1829', 'Landmine Squat to Press', ARRAY['shoulders','glutes','quads','hamstrings','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1830', 'Barbell Step Back Lunge', ARRAY['quads'], ARRAY['barbell'], 'strength', ARRAY['Barbell Reverse Lunge']),
  ('wger:1831', 'Hammerstrength Decline Chest Press', ARRAY['chest','shoulders','triceps'], ARRAY[]::text[], 'strength', ARRAY['Hammerstrength Decline Press']),
  ('wger:1832', 'Ring Support Hold', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1833', 'Floor Glider Hamstring Curls', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1834', 'Trap-3 Raise', ARRAY['back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1835', 'External Rotation Stretch', ARRAY['shoulders','back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1838', 'Banded Shoulder Drills', ARRAY['shoulders','chest','back'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1839', 'Solo Hip Flexor Stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1840', 'Bent-Leg Hamstring Stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1841', 'Seated Shoulder Extension Stretch', ARRAY['back','chest'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1846', 'Horse Stance (Side Splits)', ARRAY['glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1854', 'Calves foam roller', ARRAY['calves'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1855', 'Hamstring Foam roller', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1856', 'Foam Roller Anterior tibialis', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1857', 'Foam Roller Iliotibial band', ARRAY['quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1858', 'Foam Roller quadriceps', ARRAY['quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1859', 'Foam Roller Gluteus', ARRAY['glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1860', 'Foam Roller Adductors', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1861', 'Side stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1862', 'Hip Circles', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1863', 'Hip Crossover', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1864', 'Ankle Roll', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1865', 'Banded Ankle Mobility', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1867', 'Hip Flexor Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1868', 'Lunge with Twist Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1869', 'Lying Figure Four Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1870', 'Lying Hamstring Stretch with Band', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1871', 'Lying Knee to Chest Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1872', 'Pigeon Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1873', 'Quad Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1874', 'Runners Lunge Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1875', 'Standing IT Band Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1876', 'Supported Calf Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1877', 'Banded Scapular Retraction', ARRAY['shoulders','back'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1879', 'Incline DB Y-Raise', ARRAY['shoulders','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1881', 'DB Wrist Extension', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1882', 'High-Cable Lateral Raise', ARRAY['shoulders','back','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1883', 'Machine Chest Press', ARRAY['chest','shoulders','biceps','full_body','triceps'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1776', 'Suitcase Carry', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1801', 'Barbell Full Squat', ARRAY['hamstrings','glutes','quads','calves','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1807', 'Behind the Back Cable Lateral Raise', ARRAY['shoulders','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1823', 'Clamshell', ARRAY['glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1842', 'Banded Clamshell', ARRAY['glutes','core','quads'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1397', 'Standing Pancake Good Morning', ARRAY['hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY['Wide-Stance Good Morning']),
  ('wger:1845', 'Seated Pancake Good Morning', ARRAY['glutes'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1884', 'Shinbox IR Stretch', ARRAY['glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1885', 'YTWL Exercise', ARRAY['shoulders','back'], ARRAY['dumbbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:1886', 'Supine Hip Abduction', ARRAY['glutes','quads'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1939', 'Neck CARs', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1943', 'Neck CARs', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1947', 'dumbbell snatch', ARRAY['hamstrings','glutes','quads'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1948', '1 Leg Box Squat', ARRAY['hamstrings','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1893', 'Overhead Barbell Press', ARRAY['shoulders'], ARRAY['barbell'], 'strength', ARRAY['Military Press']),
  ('wger:1949', 'Limber 11', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1950', 'Foam Roll IT Band', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1953', 'Bent-knee Iron Cross', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1897', 'Close-Grip Bench Press', ARRAY['triceps','chest'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1956', 'Fire Hydrant Circles', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1959', 'Seated Piriformis Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1900', 'Tricep Rope Pushdowns', ARRAY['triceps','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1901', 'Clean and Press', ARRAY['shoulders','quads'], ARRAY['barbell'], 'strength', ARRAY['Clean & Press','Barbell Clean and Press','Olympic Clean and Press']),
  ('wger:1902', 'Weighted push-ups', ARRAY['chest','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1903', 'Walking Lunges', ARRAY['quads','glutes'], ARRAY['resistance_band'], 'strength', ARRAY['Forward Walking Lunges','Stepping Lunges','Dynamic Lunges','Walking Dumbbell Lunges','Alternating Lunges (Walking)','Dynamic Lunges','Forward Walking Lunges']),
  ('wger:1904', 'Pec Deck', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1905', 'Pullback', ARRAY['biceps','back','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1906', 'Hip Bridge', ARRAY['glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1907', 'Unilateral Lunges', ARRAY['glutes','quads','hamstrings'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1908', 'Butterfly Superman', ARRAY['back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1909', 'Leg Wheel', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1910', 'Kneeling Superman', ARRAY['hamstrings','back','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1911', 'Cat Plank', ARRAY['quads','core','shoulders'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1912', 'Core Rotation', ARRAY['quads','core','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1913', 'Unilateral Hip Thrust', ARRAY['glutes','core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1914', 'Isometria alle parallele', ARRAY['chest','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1915', 'Quadruped Hip Abduction', ARRAY[]::text[], ARRAY['resistance_band','bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1916', 'Tuck planche', ARRAY['shoulders','core','full_body','chest','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1918', 'Legend Chest Press', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1919', 'Extreme Pec Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1920', 'Extreme Shoulder Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1921', 'Extreme Lat Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1922', 'Seated Cable chest fly', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1924', '3008 Abdominal Crunch', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY['3008 Klappsitz']),
  ('wger:1925', 'Barbell Silverback Shrug', ARRAY['back'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1927', 'Inverted Lat Pull Down', ARRAY['back','biceps','full_body','core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1928', 'Seated V-Grip Row', ARRAY['back','shoulders','biceps','core','full_body'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1929', 'Assisted Pull-Up', ARRAY['back','shoulders','biceps','core','full_body'], ARRAY['resistance_band'], 'strength', ARRAY[]::text[]),
  ('wger:1931', 'Dumbbell Curl', ARRAY['biceps','full_body','shoulders','core'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1933', 'Abdominal Crunch', ARRAY['core','full_body'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1935', 'Belt Squat', ARRAY['glutes','quads','hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:20', 'Arnold Shoulder Press', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY['Schwarzenegger Press','Palm-to-Palm Overhead Press','Rotational Dumbbell Press','Dumbbell Corkscrew Press']),
  ('wger:43', 'Barbell Hack Squats', ARRAY[]::text[], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:801', 'Dumbbell Push-Up', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:46', 'Barbell Lunges Standing', ARRAY['quads','glutes'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:802', 'Barbell Lunges Walking', ARRAY[]::text[], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:50', 'Barbell Triceps Extension', ARRAY['triceps','shoulders','chest'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:48', 'Barbell Reverse Wrist Curl', ARRAY[]::text[], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:984', 'Lunges', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:986', 'Side split squats left', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:987', 'Side split squats right', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:988', 'Bulgarian split squats left', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:989', 'Bulgarian split squats right', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:991', 'Split squats left', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:992', 'Split squats right', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:994', 'Forward arm circles', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:995', 'Backward arm circles', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:999', 'Reverse lunges', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1001', 'High plank', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:92', 'Biceps Curls With Dumbbell', ARRAY['biceps','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:83', 'Bent Over Rowing', ARRAY['back','shoulders','biceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:81', 'Bent Over Dumbbell Rows', ARRAY['back'], ARRAY['bench','dumbbell'], 'strength', ARRAY['One Arm DB Rows']),
  ('wger:94', 'Biceps Curls With SZ-bar', ARRAY['biceps','full_body'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:82', 'Bent-over Lateral Raises', ARRAY[]::text[], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:75', 'Benchpress Dumbbells', ARRAY['chest','shoulders','triceps'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:91', 'Biceps Curls With Barbell', ARRAY['biceps','full_body'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1889', 'Decline Bench Leg Raise', ARRAY['core'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:1936', 'Cable Rear-Delt Fly (single arm)', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:723', 'Wide-grip Pulldown', ARRAY['back','shoulders','full_body'], ARRAY[]::text[], 'strength', ARRAY['Lat Pulldown (Wide Grip)','Lat Pulldown (Wide Grip)']),
  ('wger:73', 'Bench Press', ARRAY['chest','shoulders','triceps'], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:76', 'Bench Press Narrow Grip', ARRAY['triceps','shoulders','chest'], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:95', 'Biceps Curl With Cable', ARRAY['biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:803', 'One Arm Triceps Extensions on Cable', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:71', 'Single Leg Extension', ARRAY['quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1004', 'Forward shoulder rotation', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1005', 'Backward shoulder rotation', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1008', 'Left neck stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1009', 'Right neck stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:822', 'Cable Rear Delt Fly', ARRAY['shoulders','back','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:12', 'Seated Hip Adduction', ARRAY['glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:56', 'Abdominal Stabilization', ARRAY['core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:1013', 'Left levator scapulae stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1014', 'Right levator scapulae stretch', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1015', 'Clockwise neck circles', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1016', 'Counterclockwise neck circles', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1017', 'Neck half circles', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1019', 'Side plank right', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1020', 'Pistol squats right', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1021', 'Calf raises, right leg', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:265', 'Glute Bridge', ARRAY['glutes','hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:158', 'Close-grip Lat Pull Down', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:124', 'Braced Squat', ARRAY['quads','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:51', 'Barbell Wrist Curl', ARRAY['shoulders','hamstrings','biceps','core'], ARRAY['barbell','bench'], 'strength', ARRAY['Forearm Curls']),
  ('wger:146', 'Calf Press Using Leg Press Machine', ARRAY['calves','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:148', 'Calf Raises on Hackenschmitt Machine', ARRAY['calves','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:137', 'Butterfly Narrow Grip', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:165', 'Ball crunches', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:135', 'Butterfly', ARRAY['chest','shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:172', 'Crunches on Machine', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:171', 'Incline Crunches', ARRAY['core'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:139', 'Butterfly Reverse', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:167', 'Crunches', ARRAY['core','full_body'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:174', 'Crunches With Legs Up', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:189', 'Deficit Deadlift', ARRAY['hamstrings','glutes','back','core','full_body'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:235', 'Flutter Kicks', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:184', 'Deadlifts', ARRAY['back','glutes'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:193', 'Diagonal Shoulder Press', ARRAY[]::text[], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:203', 'Dumbbell Goblet Squat', ARRAY['quads'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:185', 'Decline Bench Press Barbell', ARRAY['chest'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:186', 'Decline Bench Press Dumbbell', ARRAY['chest'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:205', 'Dumbbell Lunges Standing', ARRAY['quads','glutes'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:188', 'Decline Pushups', ARRAY['chest','shoulders'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:237', 'Fly With Cable', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:206', 'Dumbbell Lunges Walking', ARRAY['quads','glutes'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:239', 'Fly With Dumbbells, Decline Bench', ARRAY['chest'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:238', 'Fly With Dumbbells', ARRAY['chest'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:204', 'Dumbbell Incline Curl', ARRAY['biceps','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:211', 'Dumbbell Triceps Extension', ARRAY['triceps','shoulders','chest'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:194', 'Dips', ARRAY['chest','triceps'], ARRAY['bodyweight'], 'strength', ARRAY['Weighted Dips']),
  ('wger:197', 'Dips Between Two Benches', ARRAY['triceps'], ARRAY['bench'], 'strength', ARRAY[]::text[]),
  ('wger:254', 'Front Raises with Plates', ARRAY['shoulders','back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:283', 'Hanging Leg Raises', ARRAY['core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:256', 'Front Raises', ARRAY['shoulders'], ARRAY['barbell','dumbbell'], 'strength', ARRAY['dumbbell front raises','DB Front Raises']),
  ('wger:291', 'Hindu Squats', ARRAY['quads','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:257', 'Front Squats', ARRAY['glutes','core'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:275', 'Hammercurls on Cable', ARRAY['biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:272', 'Hammer Curls', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:245', 'Skullcrusher Dumbbells', ARRAY['triceps'], ARRAY['bench','dumbbell'], 'strength', ARRAY['French Press Dumbbells']),
  ('wger:246', 'Skullcrusher SZ-bar', ARRAY['triceps'], ARRAY['bench','other'], 'strength', ARRAY['French Press SZ-bar']),
  ('wger:259', 'Front Pull narrow', ARRAY['back','biceps','full_body'], ARRAY['barbell','other'], 'strength', ARRAY[]::text[]),
  ('wger:258', 'Front pull wide', ARRAY['back','shoulders','biceps','full_body'], ARRAY['barbell','other'], 'strength', ARRAY[]::text[]),
  ('wger:282', 'Handstand Pushup', ARRAY['back','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:365', 'Leg Curls (laying)', ARRAY['hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:354', 'Lat Pull Down (Leaning Back)', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:355', 'Lat Pull Down (Straight Back)', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:366', 'Leg Curls (sitting)', ARRAY['hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:349', 'Lateral Rows on Cable, One Armed', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY['Side raises on Cable']),
  ('wger:348', 'Lateral Raises', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY['Shoulder fly','Side raises']),
  ('wger:364', 'Leg Curl', ARRAY['hamstrings','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:351', 'Lateral-to-Front Raises', ARRAY['shoulders','back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:313', 'Incline Push up', ARRAY['chest','hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:341', 'Squats on Multipress', ARRAY['quads','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:308', 'Incline Dumbbell Fly', ARRAY['chest'], ARRAY['dumbbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:312', 'Incline Plank With Alternate Floor Touch', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:331', 'Kettlebell Swings', ARRAY['glutes','hamstrings'], ARRAY['kettlebell'], 'strength', ARRAY[]::text[]),
  ('wger:380', 'Leverage Machine Iso Row', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:427', 'Negative Crunches', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:418', 'Military Press mit SZ-Bar', ARRAY[]::text[], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:386', 'Diamond push ups', ARRAY['chest','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:378', 'Leg Raises, Standing', ARRAY['core','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:379', 'Leverage Machine Chest Press', ARRAY['chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:377', 'Leg Raises, Lying', ARRAY['core','full_body'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:376', 'Leg Raise', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:397', 'Low Box Squat - Wide Stance', ARRAY['glutes','quads'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:367', 'Leg Curls (standing)', ARRAY['hamstrings'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:375', 'Leg Press on Hackenschmidt Machine', ARRAY['quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:373', 'Leg Presses (narrow)', ARRAY['quads','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:374', 'Leg Presses (wide)', ARRAY['quads','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:371', 'Leg Press', ARRAY['hamstrings','calves','glutes','quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:448', 'Pendelay Rows', ARRAY['back','biceps','triceps'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:484', 'Rack Deadlift', ARRAY['glutes','biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:478', 'Push Press', ARRAY['back','glutes'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:445', 'Pause Bench', ARRAY['chest','triceps'], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:465', 'Preacher Curls', ARRAY['full_body'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:487', 'Rear Delt Raises', ARRAY[]::text[], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:456', 'Pistol Squat', ARRAY['hamstrings','glutes','shoulders','biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:477', 'Pull Ups on Machine', ARRAY['back','shoulders','biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:475', 'Pull-ups', ARRAY['back','shoulders','biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:458', 'Plank', ARRAY['core','biceps','quads','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:545', 'Scissors', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:512', 'Rowing seated, narrow grip', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:493', 'Reverse Bar Curl', ARRAY['biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:490', 'Renegade Row', ARRAY['back'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:513', 'Rowing, T-bar', ARRAY['back','shoulders','biceps','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:549', 'Seated Triceps Press', ARRAY['triceps'], ARRAY['bench','dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:508', 'Row', ARRAY['back','quads'], ARRAY['barbell','dumbbell','other'], 'strength', ARRAY[]::text[]),
  ('wger:510', 'Rowing, Lying on Bench', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:501', 'Ring Dips', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:507', 'Romanian Deadlift', ARRAY[]::text[], ARRAY['barbell'], 'strength', ARRAY['RDL']),
  ('wger:543', 'Shoulder Press, on Machine', ARRAY['shoulders','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:498', 'Reverse Grip Bench Press', ARRAY['chest','triceps','shoulders'], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:529', 'Run - Interval Training', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:538', 'Incline Bench Press - Barbell', ARRAY['chest','shoulders','triceps'], ARRAY['barbell','bench'], 'strength', ARRAY[]::text[]),
  ('wger:562', 'Shotgun Row', ARRAY['back'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:607', 'Splinter Sit-ups', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:604', 'Speed Deadlift', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:569', 'Shoulder Press, on Multi Press', ARRAY['shoulders'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:591', 'Sit-ups', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:567', 'Shoulder Press, Dumbbells', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY['OHP Dumbbells','Overhead press Dumbbells','Military Press with Dumbbells']),
  ('wger:566', 'Shoulder Press, Barbell', ARRAY['shoulders'], ARRAY['barbell'], 'strength', ARRAY['OHP Barbell','Overhead press Barbell','Military Press with Barbell']),
  ('wger:584', 'Single-arm Preacher Curl', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:590', 'Sitting Calf Raises', ARRAY['full_body','calves'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:583', 'Side to Side Push Ups', ARRAY['shoulders','core','chest','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:598', 'Smith Machine Close-grip Bench Press', ARRAY['triceps','chest'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:576', 'Side Crunch', ARRAY['core'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:571', 'Shrugs, Barbells', ARRAY['shoulders'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:575', 'Shrugs on Multipress', ARRAY['shoulders','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:572', 'Shrugs, Dumbbells', ARRAY['shoulders'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:570', 'Shoulder Shrug', ARRAY['back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:580', 'Side Plank', ARRAY['core'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:628', 'Straight-arm Pull Down (bar Attachment)', ARRAY['back','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:632', 'Sumo Squats', ARRAY['glutes','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:629', 'Straight-arm Pull Down (rope Attachment)', ARRAY['back','triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:630', 'Sumo Deadlift', ARRAY['quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:616', 'Squat Thrust', ARRAY['glutes','quads','core','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:627', 'Stiff-legged Deadlifts', ARRAY['hamstrings','glutes'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:622', 'Standing Calf Raises', ARRAY['calves','full_body'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:614', 'Squat Jumps', ARRAY['quads'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:615', 'Squats', ARRAY['quads','glutes'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:621', 'Standing Bicep Curl', ARRAY['biceps','full_body'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:660', 'Triceps Extensions on Cable With Bar', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:711', 'Wall Handstand', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:684', 'Underhand Lat Pull Down', ARRAY['back','biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:694', 'Upright Row w/ Dumbbells', ARRAY['shoulders','back','biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:695', 'V-Bar Pulldown', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:702', 'Calf raises, one legged', ARRAY['calves'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:693', 'Upright Row, SZ-bar', ARRAY['shoulders','back','biceps'], ARRAY['other'], 'strength', ARRAY[]::text[]),
  ('wger:713', 'Wall Pushup', ARRAY['shoulders','chest','triceps','glutes','core','full_body','back'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:691', 'Upright Row, on Multi Press', ARRAY['shoulders','back','biceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:202', 'Dumbbell Concentration Curl', ARRAY['full_body','biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:441', 'Overhead Squat', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:530', 'Run - Treadmill', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:537', 'Incline Bench Press - Dumbbell', ARRAY['chest','shoulders','triceps'], ARRAY['dumbbell','bench'], 'strength', ARRAY['Incline Dumbbell Press']),
  ('wger:659', 'Triceps Extensions on Cable', ARRAY['triceps'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:674', 'Rowing with TRX band', ARRAY[]::text[], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:718', 'Wall Squat', ARRAY['hamstrings','quads'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:173', 'Crunches With Cable', ARRAY['core'], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1084', 'Dumbbell Floor Press', ARRAY['chest','shoulders','biceps','triceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1688', 'Kickstand RDL', ARRAY['hamstrings'], ARRAY['barbell'], 'strength', ARRAY[]::text[]),
  ('wger:1567', 'Alternating dumbbell hammer curl', ARRAY['biceps'], ARRAY['dumbbell'], 'strength', ARRAY[]::text[]),
  ('wger:1847', 'Straddle L-Sit', ARRAY['core','back','chest','quads','full_body'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1852', 'L-sit', ARRAY['back','chest','core','quads','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1853', 'L-Sit (Foot Supported)', ARRAY['back','chest','core','full_body','quads','triceps'], ARRAY['bodyweight'], 'strength', ARRAY[]::text[]),
  ('wger:1940', 'Diaphragmatic Breathing', ARRAY[]::text[], ARRAY[]::text[], 'cardio', ARRAY[]::text[]),
  ('wger:1951', 'Foam Roll Adductors', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1954', 'Roll-overs into V-sits', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[]),
  ('wger:1960', 'Rear-foot-elevated Hip Flexor Stretch', ARRAY[]::text[], ARRAY[]::text[], 'strength', ARRAY[]::text[])
) AS v(external_id, name, muscle_groups, equipment, category, search_aliases)
ON CONFLICT (external_id) WHERE external_id IS NOT NULL DO NOTHING;
